### ISSUE TITLE
CoNLL-U support

### ISSUE THREAD

**Issue by brgsk** [shtoshni/fast-coref#1]
Hi, thanks so much for this, great work!
I'm working on coreference resolution for Polish, and do have data in `.conllu` format. I would love to see how to implement `.conllu` preprocessing into your pipeline!

**Comment by shtoshni** [comment]
Thanks, @bartoszkroguski!
I have not looked into this at all. A cursory search suggests that this [repo](https://pypi.org/project/conllu/) might be of relevance. In terms of this repo, I believe the [data_processing](https://github.com/shtoshni/fast-coref/tree/main/src/data_processing) package/sub-directory is the only one that should be affected.

**Comment by brgsk** [comment]
Great, thanks! 
Btw: is any benchmark with other SOTAs available anywhere? Would be great to compare the results.
