### ISSUE TITLE
How to fine-tune on a custom dataset?

### ISSUE THREAD

**Issue by yxliao95** [shtoshni/fast-coref#11]
Hi @shtoshni , thanks for the great work. 

I'm new to this field, but resolving the coreference is one of the intermediate processes in my research. And my data are different from the publicly available dataset, which means I need to annotate the data and fine-tune an existing model to fit the data. 

I was wondering if this model can be fine-tuned on a custom dataset? And if yes, could you provide any tutorial/suggestion on how to fine-tune the model, and what the data look like as the model need? Any suggestion would greatly save me the time of reading the code.

**Comment by shtoshni** [comment]
Interesting. I would use one of the pretrained models released and fine-tuning that model on your dataset. My co-author's, Patrick Xia, [work](https://aclanthology.org/2021.emnlp-main.425.pdf) would be a good read as it suggests a few recipes for transferring a pretrained coreference model. 

Regarding your questions on data etc., I would suggest looking at [LitBank](https://github.com/dbamman/litbank/tree/master/coref) annotations. I think you can avoid reading the codebase for initial experiments and just do away with reading the README. You might need to read the code if you need to modify the code for some very specific requirements. But I feel most of the work can be accomplished by properly modifying the config files.

**Comment by yxliao95** [comment]
Thanks for the suggestions. I would have a look then.
