### ISSUE TITLE
Regarding the PreCo dataset

### ISSUE THREAD

**Issue by KawshikManikantan** [shtoshni/fast-coref#15]
The PreCo dataset (https://preschool-lab.github.io/PreCo/) seems to be unavailable as no email was received for many days after filling in the details on the page. Though I know this is not an issue of this repository, I could not place my hands on it anywhere and thought maybe the authors or the community can help me here. Can someone point me to any version of the dataset available elsewhere?
Thank you

**Comment by shtoshni** [comment]
Hey try this is the link I got from the authors - https://drive.google.com/file/d/1q0oMt1Ynitsww9GkuhuwNZNq6SjByu-Y/view?usp=sharing
