### ISSUE TITLE
PreCo dev data

### ISSUE THREAD

**Issue by WenzhengZhang** [shtoshni/fast-coref#17]
Hi,

I downloaded the PreCo data [here](https://github.com/shtoshni/fast-coref/issues/15), which only contains training and dev data. From your paper, it seems that you held out 500 docs from training data as your dev data and treat the original dev data as test data? Did you randomly sample 500 docs or take the last 500 docs from the training data as your dev data?

**Comment by shtoshni** [comment]
Last 500 docs as dev. Sorry for the late reply!
