### ISSUE TITLE
Feature Request: Python Package

### ISSUE THREAD

**Issue by sondalex** [shtoshni/fast-coref#18]
Hi @shtoshni, thank you for this project.

I was wondering if there are any future plans to organize this project as a Python package?

**Comment by shtoshni** [comment]
Umm, I wasn't planning on doing it, tbh. But I'll let you know if that changes.

**Comment by sondalex** [comment]
Thank you 😄

**Comment by shtoshni** [comment]
You can try this BTW - https://pypi.org/project/fastcoref/
