### ISSUE TITLE
Error with memory bounded model

### ISSUE THREAD

**Issue by andreasvc** [shtoshni/fast-coref#2]
On this line: https://github.com/shtoshni/fast-coref/blob/f5f41f0e19f37594f2c85dc6f3eecddec91cda52/src/model/memory/entity_memory_bounded.py#L193

I get an error that the parameter `lru_list` is unexpected.

I fixed it by adding `**ignore` as an extra parameter to `initialize_merory()` in `base_memory.py`; is this a proper fix or should it be fixed another way?

**Comment by shtoshni** [comment]
Thanks for pointing out this issue! I have fixed it with **kwargs.
