### ISSUE TITLE
Training on litbank dataset

### ISSUE THREAD

**Issue by aakashb95** [shtoshni/fast-coref#4]
I am modifying a few clusters from the litbank dataset. How do I create the jsonlines for my custom litbank dataset like the one you have in your google drive? 

And ones I have the jsonlines, then i should run the following right?:
```shell
python main.py experiment=litbank trainer.label_smoothing_wt=0.0
```

**Comment by shtoshni** [comment]
Modify the CoNLL files for Litbank and then reprocess the data as follows:
```
python data_processing/process_litbank.py ../../coref_resources/data/litbank/conll
```

And regarding retraining, yes that's the procedure to train the model.

**Comment by aakashb95** [comment]
Thanks for the instructions. Needed some help with the conll files which I was able to get from [here](https://github.com/shtoshni/long-doc-coref/blob/master/README.md).
