### ISSUE TITLE
mention index mismatch

### ISSUE THREAD

**Issue by aakashb95** [shtoshni/fast-coref#5]
![image](https://user-images.githubusercontent.com/48802744/149579581-fd04d686-ce09-435d-9344-668523c1dfb5.png)

tiny fix needed here:
https://github.com/shtoshni/fast-coref/blob/f5f41f0e19f37594f2c85dc6f3eecddec91cda52/src/inference/model_inference.py#L66

need to append(subtoken_map[ment_start], subtoken_map[ment_end])

**Comment by shtoshni** [comment]
Thanks for the pull request. It was more of a design choice that I had chosen to use the tokenized indices in the output. 
There was a minor bracketing mistake which I've fixed.
