### ISSUE TITLE
References indexes are not compatible with source sentence.

### ISSUE THREAD

**Issue by ierezell** [shtoshni/fast-coref#7]
From a coreference dataset :
(Tune: \`\`A Dream is a Wish Your Heart Makes'') Alice in Wonderland - Alice sings, while the garden of live flowers judge her. (Tune: \`\`All in the Golden Afternoon'') Peter Pan - Michael watches while Wendy assists Peter with his shadow.

The decoded tokens gives :
( Tune : \` \` A Dream is a Wish Your Heart Makes '' ) Alice in Wonderland - Alice sings, while the garden of live flowers judge her. ( Tune : \` \` All in the Golden Afternoon '' ) Peter Pan - Michael watches while Wendy assists Peter with his shadow.

(Note the spaces at each : \` ) ( " )

Then the reference indexes are correct within the decoded sentence but it's impossible to find the real character indexes in the source sentence.

Like :
'William de Alwis (1842--1916) was a Ceylonese artist and entomologist. With his brother George (dates unknown), William made a lasting contribution to the knowledge of the lepidoptera, (butterflies and moths) of Ceylon.'

And the ref text or decoded token text is : 'William de Alwis ( 1842 - -1916 )' which can't be found in the source sentence....

I guess this is all caused by spacy tokenization which runs firsts.

Thanks in advance for any help,
Have a great day

**Comment by ierezell** [comment]
For the posterity or anyone having the same troubles : 

I made a fallback + fuzzy search to retrieve the reference in the original text. 
This can find and give correct character indexes of `William de Alwis (1842--1916)` from `William de Alwis ( 1842 - -1916 )` (in the example above)

(Note that self is just a wrapper for this package and `self.model` is an fast-coref `Inference` class)
```python 
from typing import Any, List, Optional, Tuple

import regex
SPACY_SPECIAL_CHARS = "`.,*-'!?/:;()[]{}<>�"


def decode(self, tokens: List[int]) -> str:
        string = "".join(
            self.model.tokenizer.batch_decode(
                tokens,
                skip_special_tokens=True,
                clean_up_tokenization_spaces=True,
            )
        ).strip()
        return string

    def find_start(
        self,
        reference: Tuple[Tuple[int, int], str],
        full_text: str,
        source_tokens: List[int],
        tokens: List[int],
    ) -> Tuple[int, str]:
        text = reference[1]
        # Search the exact text in the full text : offset on the reference of source_tokens
        text_until_ref = self.decode(source_tokens[: reference[0][0]])
        spec_char_ref = sum(
            [text_until_ref.count(char) for char in SPACY_SPECIAL_CHARS]
        )
        start = full_text.find(text, len(text_until_ref) - spec_char_ref)

        if start != -1:
            return start, text

        # Search the exact text in the full text : offset on the reference of tokens
        text_until_ref_2 = self.decode(tokens[: reference[0][0]])
        spec_char_ref_2 = sum(
            [text_until_ref_2.count(char) for char in SPACY_SPECIAL_CHARS]
        )
        start = full_text.find(text, len(text_until_ref_2) - spec_char_ref_2)

        if start != -1:
            return start, text

        total_special_characters_text = sum(
            [text.count(char) * 3 for char in SPACY_SPECIAL_CHARS]
        )

        # Fuzzy find the text (as spaces are inserted because of the model)
        for i in range(2, total_special_characters_text + 3):
            reference_text = regex.search(
                pattern=rf"({regex.escape(text)}){{e<{i}}}",
                string=full_text,
                pos=len(text_until_ref) - spec_char_ref,
            )

            if reference_text:
                # Do a classic find instead of group position to get rid of spaces
                start = full_text.find(
                    reference_text.group(0).strip(),
                    len(text_until_ref) - spec_char_ref,
                )
                if start != -1:
                    return start, reference_text.group(0).strip()

                start = full_text.find(
                    reference_text.group(0).strip(),
                    len(text_until_ref_2) - spec_char_ref_2,
                )

                if start != -1:
                    return start, reference_text.group(0).strip()

        raise AssertionError("Could not find the reference start") # this should not happen.. maybe you miss a character in the spacy list above ?
```

and call it with 
```python
joined_text = ".\n".join(texts) # texts is a list of string
res: Any = self.model.perform_coreference(document=joined_text)
res_clusters: List[List[Tuple[Tuple[int, int], str]]] = res["clusters"]
tokens: List[int] = res["tokenized_doc"]["sentences"][0] # tokenized but with spacy and thus more spaces
source_tokens: List[int] = self.model.tokenizer.encode(joined_text) # tokenized without spaces

clusters: List[Cluster] = []
for idx_cluster, ref in enumerate(res_clusters):
    if len(ref) < 2:
        continue

    references: List[Reference] = []
    main_ref = ref[0]
    main_start, main_text = self.find_start(main_ref, joined_text, source_tokens, tokens)
```

**Comment by ierezell** [comment]
Note that it's also possible to load spacy without some element to have it more light and fast : 

```python
 self.basic_tokenizer = spacy.load(
            "en_core_web_sm",
            exclude=[
                "ner",
                "tok2vec",
                "entity_linker",
                "entity_ruler",
                "text_cat",
                "textcat_multilabel",
                "transformer",
            ],
        )
```

**Comment by shtoshni** [comment]
Thanks, @Ierezell for pointing out this issue. As you said, this is because of the spacy tokenizer. Spacy was required because while the training datasets are typically well tokenized, the inference time documents need not be. With BPE tokenizers, having a space in prefix or not having one can completely change the tokenization output. So to bridge this gap between training and inference, I resorted to using spacy as a basic tokenizer.
