### ISSUE TITLE
Dialogue coreference

### ISSUE THREAD

**Issue by maherr13** [shtoshni/fast-coref#8]
Can this repo be used for conversational coreference?

**Comment by shtoshni** [comment]
I think so. In fact, OntoNotes has a few conversational documents. 
The key is to denote speakers in the text if that information is available.  
[Here's](https://github.com/shtoshni/fast-coref/blob/5c79949377b5d72d917fc781444dd252de247cc9/src/data_processing/process_ontonotes.py#L101) how we did it for OntoNotes.

**Comment by maherr13** [comment]
Great!

If I may ask, what should be the dialogue format so that I can use it with the model?

**Comment by shtoshni** [comment]
[SPEAKER_START] speaker1 [SPEAKER_END] dialog1 [SPEAKER_START] speaker2 [SPEAKER_END] dialog2. 

[SPEAKER_START] and [SPEAKER_END] are special tokens we used in our model. They are a part of [the model trained on OntoNotes](https://huggingface.co/shtoshni/longformer_coreference_ontonotes) that we've released. See the [added_token file](https://huggingface.co/shtoshni/longformer_coreference_ontonotes/blob/main/added_tokens.json). I would suggest playing with [the Colab demo](https://colab.research.google.com/drive/11ejXc1wDqzUxpgRH1nLvqEifAX30Z71_?usp=sharing) to get things started.

**Comment by maherr13** [comment]
Many Thanks

**Comment by maherr13** [comment]
Hey again, 

I noticed that the model (in the case of dialogue) doesn't detect the speaker's name unless its mentioned in the context here is an example :

![image](https://user-images.githubusercontent.com/83926003/167495944-30fffd95-65f8-4392-805d-ae2dfa269d7b.png)

and the cluster for the reporter is 

![image](https://user-images.githubusercontent.com/83926003/167496065-4684ca84-1ba5-48fc-bcbb-74b6005b8158.png)

so is there a way (specific format for the dialogue) to detect the reporter among the cluster?

**Comment by maherr13** [comment]
Hey again,

I noticed that the model (in the case of dialogue) doesn't detect the speaker's name unless its mentioned in the context here is an example :

![image](https://user-images.githubusercontent.com/83926003/167497900-b44131eb-c6b0-4cc5-934f-e1e92d98d9c4.png)

and the cluster for the reporter is

![image](https://user-images.githubusercontent.com/83926003/167497863-6000f8f8-7029-4f7e-a597-ab61b680afa1.png)

so is there a way (specific format for the dialogue) to detect the reporter among the cluster?

**Comment by shtoshni** [comment]
Ahh it would be difficult because OntoNotes doesn't annotate the speaker's span. So the model doesn't learn to mark that as part of the cluster.

**Comment by maherr13** [comment]
Ok thanks for you help
